cbsi_product_listing:
    pattern:  /products
    defaults: { _controller: CBSiProductBundle:Default:showProducts }

cbsi_product_single:
    pattern: /product/{id}
    defaults: { _controller: CBSiProductBundle:Default:showSingle }
