parameters:
#    cb_si_product.example.class: CBSi\ProductBundle\Example

services:
#    cb_si_product.example:
#        class: %cb_si_product.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
    Product.ApiClient:
        class: CBSi\ProductBundle\ApiClient
        arguments: ["http://ec2-184-169-221-118.us-west-1.compute.amazonaws.com/"]